{% set name = "VIC" %}
{% set version = "5.0.1" %}
{% set sha256 = "05cdc39a80ad175f5a9d17fbf5a414f1ff069ddc8b1c76f2e3d66cbfc93f9522" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UW-Hydro/{{ name }}/archive/{{ name }}.{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - cc-env.patch  # backport https://github.com/UW-Hydro/VIC/pull/894

build:
  number: 2
  skip: True  # [win]

requirements:
  build:
    - make
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - mpich
    - openmp
    - libnetcdf
    - cffi
  run:
    - python
    - mpich
    - libnetcdf
    - cffi
test:
  imports:
    - vic
  commands:
    - vic_classic.exe -v
    - vic_classic.exe -o
    - vic_image.exe -v
    - vic_image.exe -o

about:
  home: http://github.com/UW-Hydro/vic
  license: GPL-2
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Variable Infiltration Capacity (VIC) Macroscale Hydrologic Model'
  description: |
    VIC (Liang et al., 1994) is a macroscale hydrologic model that solves full
    water and energy balances, originally developed by Xu Liang at the University
    of Washington. VIC is a research model and in its various forms it has been
    applied to most of the major river basins around the world, as well a
    globally.
  doc_url: http://vic.readthedocs.io/
  dev_url: https://github.com/UW-Hydro/vic

extra:
  recipe-maintainers:
    - jhamman
    - bartnijssen
    - tbohn
