# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "MQ6+eCEICOK2y1ZesGK21iHgpmTavoAXT5gHe3fHAfcbNK3iIVN7/NKvDuWoyPsjYTZ4D35ECUtKFdEceJc+e+5ZpJW6CKVwVbBh524N5IOsTKvxlXRoKaHu/ndjTd/pOdVwjlnJCONi/0It7TEmY83ETt/GTlHTHEhTrOZHVCFCz35df79Bz39BE5Ff73Ve4pbaAtHyHVs8NTlBQMILQiAx0Z7P43/k1NBY7UicdtxscNtfI5GMihn5MP9WzFt5oFgYKXB3ALM0ZOwccHlvrYX6oZxS4zwA8GwnHCCSb+ubkOKwosokyB4xbGtrDmekWxZ+OwLEu9V+ppIBd4MY9eAkfXMp1bAdqluS4ikN430RlpA7yFoPrBIVDsGRPgDNsUzoVdQ2KS+cCGpfIy2mPioN2y/hrQnFEk/PVjJUqhhY56j6fytmzL2d/JHhL14zA90d7k+A25xa1jveu3gWoaKybU0Z4nll7+J/Io2namvi+vK6dsjQNyqEalx+L0FzthQwi9ioCN9bfpqQv1piBuL5bZ+erJ4uLw/cGNcpM5O9zH1/Y873QYUE2U+TCLUsWzzJkzXovrYlwKo7LHHvvL3bcGDf7lNNslxESAJYYNGEm44BZJVFJVFmtDClJd3t3dXwls+gxFLFj/csIoxhsSGG1Nqf5JhphbZf7K96Hs4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
