# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "h/aJ7z5UDOWfYx318edvTLk2ljyf9CSCVnUbU048WSY+0/KP8X7t17BbP+fFIQ4XaMzdtmY52UYQpVeoabNu0RVE0gn2evzRbL1AC+6jW4HZLJhS2l+2BkrR6KFrWA4ftz4B5fQfpI5goxHNWKDQsMN+jl7tlSALeQvdRiMsFesoZDj7IH7GMgJTbSbOn2v6avmE4C0WjNOIPzNI54EMjsXo6YzkunBPSyKaDp1yPPb+Y9yiSA+StQUAlyuo8bc56On3tf5WQzwLzOKLchXC0oSIsjR4F2GehF6sDCf/WfP9661HlH0YRsqmPLw7YRlTx7j2StknyWBK4a+Bv7uLEolOSZR8e6VHNCcT1WfKctMGKzjZ5v2APUY+4a5CeTYgdXph92cxaQm+YInHiTw/EKrchugWRl2dslAUkrHfGHuzoRFhv2OkR6kwW0iTseu8aZpOmYPGT7G/o9asjXtHB/3IDolq3f7EnB3FK5EdoT72Diin4ECM3bTJJDX/nfApNp2ZVhya92ccuOs0qlD0WiaKVrVPONVPQv9cJDiqGLb3gI4tgCmjzk4iyrrqeEADFi3Rnh+wcbNuC7acPtbf3zRJF2YIzAdy+fiC7JtcnZN08P9S/7aoD83kGLV7EPk0VC5VBdzrOO/uPM5rwrxEZ+xaldDRdj55w1GzARumc7w="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
