travis:
  secure:
    BINSTAR_TOKEN: h/aJ7z5UDOWfYx318edvTLk2ljyf9CSCVnUbU048WSY+0/KP8X7t17BbP+fFIQ4XaMzdtmY52UYQpVeoabNu0RVE0gn2evzRbL1AC+6jW4HZLJhS2l+2BkrR6KFrWA4ftz4B5fQfpI5goxHNWKDQsMN+jl7tlSALeQvdRiMsFesoZDj7IH7GMgJTbSbOn2v6avmE4C0WjNOIPzNI54EMjsXo6YzkunBPSyKaDp1yPPb+Y9yiSA+StQUAlyuo8bc56On3tf5WQzwLzOKLchXC0oSIsjR4F2GehF6sDCf/WfP9661HlH0YRsqmPLw7YRlTx7j2StknyWBK4a+Bv7uLEolOSZR8e6VHNCcT1WfKctMGKzjZ5v2APUY+4a5CeTYgdXph92cxaQm+YInHiTw/EKrchugWRl2dslAUkrHfGHuzoRFhv2OkR6kwW0iTseu8aZpOmYPGT7G/o9asjXtHB/3IDolq3f7EnB3FK5EdoT72Diin4ECM3bTJJDX/nfApNp2ZVhya92ccuOs0qlD0WiaKVrVPONVPQv9cJDiqGLb3gI4tgCmjzk4iyrrqeEADFi3Rnh+wcbNuC7acPtbf3zRJF2YIzAdy+fiC7JtcnZN08P9S/7aoD83kGLV7EPk0VC5VBdzrOO/uPM5rwrxEZ+xaldDRdj55w1GzARumc7w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
